/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEditProduct: typeof import('./components/common/AddEditProduct.vue')['default']
    AddProductDialog: typeof import('./components/common/AddProductDialog.vue')['default']
    AddProductForm: typeof import('./components/common/AddProductForm.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConfirmationDialog: typeof import('./components/common/ConfirmationDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainDialog: typeof import('./components/common/MainDialog.vue')['default']
    MainNavigationBar: typeof import('./components/common/MainNavigationBar.vue')['default']
    MainNavigationDrawer: typeof import('./components/common/MainNavigationDrawer.vue')['default']
    ProductDialog: typeof import('./components/common/ProductDialog.vue')['default']
    ProductsDataTable: typeof import('./components/common/ProductsDataTable.vue')['default']
    ReusableDialog: typeof import('./components/common/ReusableDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
    UserMenu: typeof import('./components/common/UserMenu.vue')['default']
    VActivatorDialog: typeof import('./components/common/dialogs/VActivatorDialog.vue')['default']
    VAddEditProduct: typeof import('./components/common/products/vAddEditProduct.vue')['default']
    VAddProduct: typeof import('./components/common/products/vAddProduct.vue')['default']
    VAddProductDialog: typeof import('./components/common/products/VAddProductDialog.vue')['default']
    VAddProductForm: typeof import('./components/common/products/VAddProductForm.vue')['default']
    VAppFooter: typeof import('./components/VAppFooter.vue')['default']
    VCategoriesDataTable: typeof import('./components/common/categories/VCategoriesDataTable.vue')['default']
    VConfirmationDialog: typeof import('./components/common/dialogs/VConfirmationDialog.vue')['default']
    VMainDialog: typeof import('./components/common/dialogs/VMainDialog.vue')['default']
    VMainNavigationBar: typeof import('./components/common/VMainNavigationBar.vue')['default']
    VMainNavigationDrawer: typeof import('./components/common/VMainNavigationDrawer.vue')['default']
    VModalDialog: typeof import('./components/common/dialogs/VModalDialog.vue')['default']
    VProductForm: typeof import('./components/common/products/VProductForm.vue')['default']
    VProductsDataTable: typeof import('./components/common/products/VProductsDataTable.vue')['default']
    VSearchProduct: typeof import('./components/common/products/VSearchProduct.vue')['default']
    VThemedDialog: typeof import('./components/common/VThemedDialog.vue')['default']
    VThemeToggle: typeof import('./components/common/VThemeToggle.vue')['default']
    VUserMenu: typeof import('./components/common/VUserMenu.vue')['default']
  }
}
